export const posts = [
  {
    id: 1,
    read: '6 min read',
    title: 'The Language of Oud',
    excerpt: "A history of the world's most precious wood — from Assam forests to Parisian perfumeries",
    date: 'July 12, 2025',
    img: '/e710b796ba3e0cfd864dbf7c31f21c2b486665e7.jpg',
    featured: true,
  },
  {
    id: 2,
    read: '6 min read',
    title: 'The Language of Oud',
    excerpt: 'A history of the world\'s most precious wood — from Assam forests to Parisian perfumeries',
    date: 'July 12, 2025',
    img: '/image 7.png',
    featured: false,
  },
  {
    id: 3,
    read: '4 min read',
    title: 'How to Layer Fragrances',
    excerpt: 'The art of building a signature scent that is entirely and unmistakably yours',
    date: 'June 28, 2025',
    img: '/Image (Unisex).png',
    featured: false,
  },
  {
    id: 4,
    read: '5 min read',
    title: 'The Perfect Gift Guide',
    excerpt: 'Fragrances that last a lifetime — curated for those who deserve something rare',
    date: 'June 10, 2025',
    img: '/image 5.png',
    featured: false,
  },
  {
    id: 5,
    read: '7 min read',
    title: 'Rose Fields of Taif',
    excerpt: 'We travelled to Saudi Arabia to witness the harvest of the world\'s most coveted rose',
    date: 'May 22, 2025',
    img: '/Image (Women).png',
    featured: false,
  },
  {
    id: 6,
    read: '3 min read',
    title: 'The Minimalist Wardrobe Scent',
    excerpt: 'One fragrance. Every occasion. How Vétiver Blanc became a modern signature',
    date: 'May 5, 2025',
    img: '/image 6.png',
    featured: false,
  },
];
